#!/bin/bash 
# Update ubuntu
sudo apt update -y 

# Install necessary tools required 
sudo apt install -y openjdk-17-jdk

# Add pkg key to add jenkins to apt repo list and install jenkins with apt
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update -y 
sudo apt-get install jenkins -y 

# Make jenkins user sudeors user
JENKINS_USER="jenkins"
sudo usermod -aG sudo $JENKINS_USER
echo "$JENKINS_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$JENKINS_USER

# Start jenkins services if no already running 
if sudo systemctl is-active --quiet jenkins; then
    echo "Jenkins service is already running."
else
    echo "Jenkins service is not running. Attempting to start Jenkins..."
    sudo systemctl start jenkins
    if sudo systemctl is-active --quiet jenkins; then
        echo "Jenkins service has been started successfully."
    else
        echo "Failed to start Jenkins service."
    fi
fi

# Display the status of the Jenkins service regardless
echo "Current status of Jenkins service:"
sudo systemctl status jenkins --no-pager

#run the below command to use this script in raw mode 
# curl -s https://raw.githubusercontent.com/jaintpharsha/install/main/jenkins-master | sudo bash 
