#!/bin/bash 

if docker --version &> /dev/null; then
    echo "Docker is already installed."
else
    echo "Installing docker ...."
    curl -s https://raw.githubusercontent.com/jaintpharsha/install/main/docker | sudo bash 
fi

echo "Create volumes for sonarqube to persist data"
docker volume create --name sonarqube_data
docker volume create --name sonarqube_logs
docker volume create --name sonarqube_extensions

docker run -d --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_USERNAME=admin \
    -e SONAR_JDBC_PASSWORD=admin \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \
    sonarqube
